paritytech/polkadot-staking-miner

- Cargo.lock
- Cargo.toml
- src/chain.rs
- src/main.rs
- src/monitor.rs
- src/prelude.rs
> fetch weight from remote node

- .gitignore
- Cargo.toml
- src/chain.rs
- src/dry_run.rs
- src/emergency_solution.rs
- src/helpers.rs
- src/main.rs
- src/monitor.rs
- src/opt.rs
single runtime
```
cargo remote run -- --release --no-default-features --features kusama  0.95s user 0.18s system 1% cpu 1:28.15 total
```
all runtimes
```
cargo remote run -- --release  0.95s user 0.18s system 0% cpu 2:13.09 total
```
specially useful if we add a node-runtime as well.
> feature gate the runtimes

- .gitlab-ci.yml
Addresses https://github.com/paritytech/staking-miner-v2/issues/406
Because of the GitLab CI specifics, when the `nightly-test` job fails due to timeout, an `after_script` section is not executed. And an artifact with job status is not created.
Workaround: test whether file `nightly_test_result` exists and if not then report `nightly-test` as failed, else read `nightly-test` status from artifact `nightly_test_result` file
> Fix CI timeout issue

- src/monitor.rs
When one runs `--listen finalized` it's possible for the block not to be finalized when it's included in block.
Thus, when that task finishes it's possible to that the `next task` will not see that submission as it is not finalized yet and submit more than one submission in a round. 
Should fix the duplicate solutions that I spotted on westend.
> fix: `--listen finalized` wait for finalized xt

- Cargo.lock
- Cargo.toml
- src/dry_run.rs
- src/epm.rs
- src/error.rs
- src/main.rs
- src/monitor.rs
- src/opt.rs
- src/prelude.rs
- src/prometheus.rs
- src/signer.rs
- tests/monitor.rs
This PR removes all git dependencies which makes it possible to release the `staking-miner` on crates.io and makes it easier to maintain in general.
> chore: upgrade subxt v0.27

- .gitlab-ci.yml
- Dockerfile.README.md
Added CI job to publish Docker image description to [hub.docker.com](https://hub.docker.com/r/paritytech/staking-miner-v2)
Description can be updated in a `Dockerfile.README.md` file in a repository root and as soon it will be merged into `main` branch its content will get published to [hub.docker.com](https://hub.docker.com/r/paritytech/staking-miner-v2)
Related to https://github.com/paritytech/ci_cd/issues/741
> ci: add ci job to publish docker image description

- src/static_types.rs
Close #472 
Basically, the EPM pallet is using `all_lt` and `all_gt` which takes the `proof_size` into account as well.
Not sure why this was triggered by the remote node must been that I updated the EPM pallet that caused this
> fix: use weight proof size

- Cargo.lock
Cargo.lock wasn't updated for the v0.1.3 release, [breaking ci](https://gitlab.parity.io/parity/mirrors/staking-miner-v2/-/jobs/2567351).
> fix: update Cargo.lock for v0.1.3

- .gitlab-ci.yml
We're in the process of phasing out the nightly rust toolchain from ci-linux, and stable seems to be sufficient for these jobs.
> use stable rust for cargo clippy and doc

- src/commands/dry_run.rs
- src/commands/emergency_solution.rs
- src/commands/mod.rs
- src/commands/monitor.rs
- src/epm.rs
- src/lib.rs
- src/main.rs
- src/opt.rs
- src/prelude.rs
- src/signer.rs
- tests/common.rs
This is a slightly opinionated reshuffle of things to:
- Make it clear what the main entry points (subcommands) are by putting them into a `commands` module.
- Put the options for each subcommand next to it (thinning out the `opts` module somewhat; maybe we can go fruther because not everything in that is related to CLI opts by the looks of it).
- Remove a couple of things from `prelude` (just because personally I think it's easier to write but harder to read/follow where things come from when `prelude::*` is used for too many imports).
What do you reckon?
> `commands` module to expose each sub-command, and put options next to them

- tests/common.rs
> fix(tests): read at most 1024 lines of logs before rpc server output

- .gitignore
- src/commands/emergency_solution.rs
- src/commands/monitor.rs
- src/epm.rs
- src/main.rs
- src/prelude.rs
Implements the `emergency_solution_cmd`, similar to the staking-miner-v1 implementation. In addition, it saves the encoded `set_emergency_solution` EPM call into a file for easy handling.
> Implements emergency solution command

- src/commands/monitor.rs
This code was copied from the staking-miner v1 but I think `submission strategy == if leading`  should really only submit if the score is strictly better than existing scores on chain. 
Thus, this is confusing and not a good default strategy such as if there is already a solution with the same score one might lose transaction fee when submitting then.
This boils down to whether one trusts that previous scores are legit or not but as we already have `submission strategy == always` that can be used if one doesn't trust the scores on chain.
//cc @kianenigma do you remember why we did it like that?
> change `submission strategy == if leading` to not submit equal score

- .gitlab-ci.yml
https://github.com/paritytech/polkadot/pull/7337 changed that polkadot requires three binaries which is required for the integration tests.
Close #642
> ci: copy new polkadot binaries to `/usr/bin`

- tests/monitor.rs
Currently, the polkadot binary doesn't provide the chainspec for `polkadot-dev` anymore
and this PR disabled it for the integration tests.
However, `kusama-dev` and `westend-dev` is still available but the `kusama-dev` will also be removed soon
> tests: disable integration tests `polkadot-dev`

- tests/common.rs
Close #710
The connection was rejected by CORS and I don't really understand why but we are not really trying to test that, thus CORS is disabled  on rpc server.
> tests: fix integration tests

- .gitlab-ci.yml
- src/commands/monitor.rs
- src/epm.rs
- src/main.rs
- src/static_types.rs
> refactor: make solution extrinsic mortal

- tests/common.rs
Close #815 
Run the polkadot node with `--unsafe-force-node-key-generation` after new changes.
> fix(test): polkadot node `--unsafe-force-node-key-generation`

- .github/workflows/build-polkadot-for-nightly.yml
- .github/workflows/build-staking-miner-playground-for-nightly.yml
- .github/workflows/ci.yml
This job fails: https://github.com/paritytech/polkadot-staking-miner/actions/runs/8961429706/job/24609041671#step:5:17 which will be fixed by updating rustc
Close https://github.com/paritytech/polkadot-staking-miner/issues/823
> fix(ci): update rustc to build polkadot

- src/epm.rs
`TrimmedVotes` uses `BTreeMap` to sort voters by stake, which results in voters with the same stake to be dropped from election.
In case if `desired_targets` == `total_voters` (on private network) it results in immediate feasibility check failure in `solution_weight`->`epm::mock_votes`, as `voters < desired_targets`.
> Fix: Feasibility check fails when all voters have the same staked amount

- .github/workflows/build-polkadot-for-nightly.yml
- .github/workflows/build-staking-miner-playground-for-nightly.yml
- .github/workflows/ci.yml
- .github/workflows/staking-miner-playground.yml
- src/helpers.rs
This fixes [the polkadot binary build](https://github.com/paritytech/polkadot-staking-miner/actions/runs/11134157706/job/30941796735) which failed because the `LazyLock` was stabilized in rust v1.80
> ci: bump rust to v1.81

- Cargo.lock
- Cargo.toml
- src/prelude.rs
polkadot-sdk has introduced the new extrinsic type bare v5, subxt v0.38 supports decoding such extrinsics which is not used yet but let's future-proof and update subxt to support  it.
> chore(deps): bump subxt v0.38 and related deps

- Cargo.toml
- src/commands/emergency_solution.rs
- src/error.rs
- src/prelude.rs
- src/signer.rs
This replaces `subxt substrate compat feature` with our own `PairSigner` to avoid depending on different versions of sp-core.
> remove `subxt substrate-compat` feature

- .github/workflows/build-polkadot-for-nightly.yml
- .github/workflows/build-staking-miner-playground-for-nightly.yml
- .github/workflows/ci.yml
Artifact actions v3 will be deprecated by December 5, 2024, updating them.
cc https://github.com/paritytech/ci_cd/issues/1078
> ci: Upgrade actions/upload-artifact and actions/download-artifact to v4

- src/commands/multi_block/monitor.rs
- src/commands/types.rs
- src/dynamic/multi_block.rs
- src/main.rs
Add the `--do-reduce` flag to the `experimental-monitor-multi-block` command.
This flag controls whether the reduction step is performed during the NPoS solution mining process for the multi-block election path.
> multi block miner: do_reduce configurable via CLI (#995)

- Cargo.lock
- Cargo.toml
- src/commands/legacy/dry_run.rs
- src/commands/legacy/monitor.rs
- src/error.rs
- src/main.rs
- src/signer.rs
- src/utils.rs
Driven-by:
- remove subxt-core as dependency and add `subxt-rpcs` as dependency
- fix compilation errors coming from the version bump of `subxt`
> Bump subxt to `0.41.0`

- README.md
Update the documentation to explicitly state that running multiple instances of the miner with the same account is not allowed. This is to prevent interference with the submission mechanism, which relies on the on-chain noise for each user.
Related issue [here](https://github.com/paritytech/polkadot-staking-miner/issues/1014)
> doc: no multiple instances of the miner with the same account

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/prometheus.rs
This commit updates the hyper dependency to version 1.6.0.
Changes:
- Updated hyper dependency in Cargo.toml
- Updated Cargo.lock with new hyper version
- Modified prometheus.rs to use the new hyper API
The changes closely match the implementation in the SDK substrate util prometheus library.
Fixes #1011
> Update hyper to v1.6.0

- .github/workflows/actions/prepare-binaries/action.yml
- .github/workflows/build-polkadot-for-nightly.yml
Commit 867fc62 (#1040) has introduced a YAML file for building polkadot for nightly with an invalid syntax, preventing the multi-block integration test to run properly.
Close #1048 , creating /etc/polkadot-staking-miner via `sudo`.
> Fix invalid build-polkadot-for-nightly.yml

- .github/workflows/build-polkadot-for-nightly.yml
- .github/workflows/build-staking-miner-playground-for-nightly.yml
- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/publish-docker-description.yml
- .github/workflows/staking-miner-playground.yml
This should fix the issue we were having with the public available runner with just 14GB of disk space, resulting in jobs failing due to no space left.
> Switch jobs to parity-large

- .github/workflows/actions/prepare-binaries/action.yml
- .github/workflows/nightly.yml
- tests/multi_block_monitor.rs
- zombienet-staking-runtimes.toml
We are uploading polkadot binaries under `target/release` in `build-polkadot-for-nightly.yml` . We should access them under `target/release`  in `action.yml` to avoid CI to file like [here](https://github.com/paritytech/polkadot-staking-miner/actions/runs/15040937569/job/42272279818).
Close #1051
> CI: fix path of polkadot binaries in action.yml

- .github/workflows/build-polkadot-for-nightly.yml
- .github/workflows/build-staking-miner-playground-for-nightly.yml
- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/publish-docker-description.yml
- .github/workflows/staking-miner-playground.yml
- tests/multi_block_monitor.rs
- zombienet-staking-runtimes.toml
We have seen the multi-block integration test failing once so far in CI/CD (see #1055). If it happens again, let's make sure to have enough info on EPMB/staking side.
Let's also make the miner itself more verbose.
NOTE: in order to be able to build the docker image via CI, we also revert #1052  and use again `ubuntu-latest` as runner, hoping not to hit again the `no disk space left` issue.
> CI/CD: more verbose logs for EPMB and staking

- .github/workflows/actions/prepare-binaries/README.md
- .github/workflows/nightly.yml
- README.md
- src/commands/multi_block/monitor.rs
- src/commands/types.rs
- src/dynamic/multi_block.rs
- src/main.rs
The changes add validation to ensure there are enough blocks remaining in the signed phase before attempting solution submission. 
This helps prevent incomplete submissions by requiring a minimum number of blocks (default 10) to complete all pages.
The validation checks remaining blocks before starting submission and between page chunks. If there’s insufficient time, it bails any incomplete submissions and skips mining new solutions.
Example:
```bash
./target/release/polkadot-staking-miner --uri ws://127.0.0.1:9946 monitor --seed-or-path //Alice --min-signed-phase-block 5
```
Close #1083.
> Add min signed phase blocks validation

- README.md
- src/commands/multi_block/monitor.rs
- src/commands/multi_block/types.rs
- src/prometheus.rs
- tests/monitor.rs
Implements automatic cleanup of old discarded submissions to reclaim deposits.
Close #980.
- Triggers when the election round increments (runs once per new round)
- Scans the last 5 rounds for old submissions at most (the usual process is to simply clear the previous round).
- Calls `clear_old_round_data()` to recover deposits and clean storage
- Non-blocking integration with existing mining operations
- Comprehensive error handling (critical vs recoverable errors)
- Introduce `JanitorMessage` enum and `janitor_task` for deposit recovery 
- Use dedicated bounded channel for janitor communication 
- Update listener to send janitor ticks to janitor task 
- Ensure mining and janitor operations are independent and non-blocking
```
┌────────────────────────────────────────────────────────────── …
```
> Added janitor task for automatic deposit recovery with Prometheus metrics

- Cargo.lock
- Cargo.toml
Now that [SDK#7997](https://github.com/paritytech/polkadot-sdk/pull/7997) has been merged, we can track SDK's  `master` branch again instead of `donal-ahm`.
> Track SDK's master branch

- README.md
- src/commands/multi_block/monitor.rs
- src/dynamic/multi_block.rs
- src/main.rs
- src/prometheus.rs
- Add subscription stall detection with a 1h timeout for the runtime upgrade task
- Add subscription stall detection with 60-second timeout and automatic recreation for the listener task
- Add new prometheus  metrics provide visibility into subscription health for alerting and debugging
- Implement comprehensive error handling in listener loop with error classification
- Refactor listener processing into inner function for better error isolation
- Add graceful recovery for storage query failures and RPC errors
- Enhance monitoring with detailed logging for subscription health
This addresses production issues where miners would stop processing blocks after subscription stalls, improving overall uptime and operational stability.
> Improve listener and updater tasks resilience with comprehensive error handling and subscription recovery

- Cargo.lock
- Cargo.toml
- src/commands/multi_block/monitor.rs
- src/dynamic/multi_block.rs
- src/main.rs
Fix breaking changes:
- Add `.clone()` for storage query parameters
- Decode raw bytes manaully when calling `call_raw()` API
> Bump to subxt 0.43.0

- src/commands/multi_block/monitor.rs
- src/main.rs
In the listener task:
1. Replaced tokio::select! with tokio::time::timeout that directly wraps subscription.next()
2. Simplified the timeout logic - now it's a straightforward 60-second timeout on each subscription call
3. Fixed the stalling issue - the timeout will always fire after 60 seconds, even if subscription.next() is stuck
The key improvement is that the timeout now wraps the potentially hanging operation directly, providing more reliable detection of a stalled subscription. This should  eliminate the future starvation issue that could prevent the original timeout from firing.
For `runtime_upgrade_task` we follow a different approach. We expect to receive a runtime upgrade very infrequently so a timeout approach doesn't work well. What we do now, is to check periodically every …
> Fix stalling issue if subscription.next() is stuck

- src/commands/multi_block/monitor.rs
- src/prometheus.rs
The listener task occasionally stalls after janitor cleanup operations, despite PR #1119's subscription timeout improvements. Critical observation: the runtime updater task continues receiving updates while sharing the same ChainClient and ChainHeadBackend, proving the underlying subscription infrastructure is presumably healthy.
This seems to suggest that the hang occurs in listener's internal processing, not in the subscription itself.
- Since updater task works, we assume subscription.next() is NOT blocking
- The hang then must occur AFTER subscription.next() returns successfully
- Current timeout only wraps subscription.next(), missing internal processing hangs
- Janitor's synchronous submit_and_watch() + wait_tx_in_finalized_block() shouldn't create transient resource contention …
> Tentatively fix listener task stalling issue with comprehensive timeout and diagnostics

- README.md
- src/commands/multi_block/monitor.rs
- src/dynamic/multi_block.rs
- src/error.rs
- src/prometheus.rs
- src/utils.rs
The staking miner would occasionally hang indefinitely when detecting new rounds, causing repeated 90-second timeouts.
We have observed this pattern on WAH, usually after few days  / a week of normal operation.
```bash
[2m2025-08-15T05:58:47.601502Z[0m [34mDEBUG[0m [2mpolkadot-staking-miner[0m[2m:[0m Detected round increment 279 -> 280
[2m2025-08-15T05:58:47.601512Z[0m [35mTRACE[0m [2mpolkadot-staking-miner[0m[2m:[0m Sent janitor tick for round 280
[2m2025-08-15T05:58:47.601514Z[0m [34mDEBUG[0m [2mpolkadot-staking-miner[0m[2m:[0m Round increment in Off phase, signaling snapshot cleanup
[2m2025-08-15T05:58:47.601532Z[0m [35mTRACE[0m [2mpolkadot-staking-miner[0m[2m:[0m Running janitor cleanup for round 280
[2m2025-08-15T05:58:47.601636Z[0m [35mTRACE[0m …
```
> Improve stalling issues with comprehensive timeout handling

- src/commands/multi_block/monitor.rs
- src/error.rs
We have seen once on WAH the staking miner entering an infinite loop when blockchain subscriptions failed, continuously recreating subscriptions every 60 seconds without limit.
Whereas the root cause of the issue needs to be investigated and fixed, we prioritize a pragmatic approach by introducing the following:
- MAX_SUBSCRIPTION_RECREATION_ATTEMPTS constant (set to 3)
- Tracking of consecutive recreation attempts in listener task
- Process exit after 3 failed recreation attempts
- Specific SubscriptionRecreationLimitExceeded error type
Logs on WAH when the issue happened (note: so far, it happened once, and never on PAH)
```bash
2025-09-15T17:50:40.087584Z TRACE polkadot-staking-miner: get_block_state: Got current_phase in 78ms: Export(12)
2025-09-15T17:50:40.087606Z TRACE …
```
> Add subscription recreation retry limit to prevent infinite loops
